-- CreateTable
CREATE TABLE "Feature" (
    "id" TEXT NOT NULL,
    "issueNumber" INTEGER NOT NULL,
    "issueUrl" TEXT NOT NULL,
    "repo" TEXT NOT NULL,
    "producto" TEXT,
    "priority" TEXT,
    "type" TEXT,
    "milestone" TEXT,
    "milestoneDate" TIMESTAMP(3),
    "githubStatus" TEXT,
    "tituloAmigable" TEXT NOT NULL,
    "descripcionCliente" TEXT,
    "featureFlag" TEXT,
    "estadoDisponibilidad" TEXT NOT NULL,
    "planMinimo" TEXT,
    "aQuienAplica" TEXT,
    "mensajeSugerido" TEXT,
    "screenshotsUrl" TEXT,
    "videoUrl" TEXT,
    "onePagerUrl" TEXT,
    "faq" TEXT,
    "notasInternas" TEXT,
    "rawComment" TEXT,
    "parseErrors" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "syncedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Feature_pkey" PRIMARY KEY ("id")
);
