-- CreateTable
CREATE TABLE "Feature" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "issueNumber" INTEGER NOT NULL,
    "issueUrl" TEXT NOT NULL,
    "repo" TEXT NOT NULL,
    "producto" TEXT,
    "priority" TEXT,
    "type" TEXT,
    "milestone" TEXT,
    "milestoneDate" DATETIME,
    "githubStatus" TEXT,
    "tituloAmigable" TEXT NOT NULL,
    "descripcionCliente" TEXT,
    "featureFlag" TEXT,
    "estadoDisponibilidad" TEXT NOT NULL,
    "planMinimo" TEXT,
    "aQuienAplica" TEXT,
    "mensajeSugerido" TEXT,
    "screenshotsUrl" TEXT,
    "videoUrl" TEXT,
    "onePagerUrl" TEXT,
    "faq" TEXT,
    "notasInternas" TEXT,
    "rawComment" TEXT,
    "parseErrors" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "syncedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
